### ISSUE TITLE
ODF 1.3 Appendix G "Changes From ODF 1.2 (Non Normative)" seems incomplete

### ISSUE THREAD

**Issue by svanteschubert** [oasis-tcs/odf-tc#37]
We started discussing this issue in our ODF TC call today:
https://lists.oasis-open.org/archives/office/202102/msg00004.html

Of the 11 deprecations, 5 are not being listed at all.
The others are listed somewhere but not under deprecations.

- 5.3.6 <text:numbered-paragraph> (deprecated) - listed in Changes Appendix under Changed elements, office-1437
- 5.3.7 Numbered Paragraph Style Rules (deprecated) - not listed
- 10.4.7 <draw:applet> (Deprecated) - listed under Changed Elements
- 10.8.4 <presentation:show-text> (deprecated) - not listed
- 19.815.2 <draw:text-box> (deprecated) an attribute of it changed
- 19.815.5 <text:changed-region> (deprecated) - not listed
- 19.815.6 <text:h> (deprecated) - not listed
- 19.815.8 <text> (deprecated) - not listed
- 19.835 text:list-id (deprecated) - listed under Changed Attributes
- 19.874.6 <text:numbered-paragraph> (deprecated) - listed under changes for text:start-value, office-1437
- 19.880.25 <text:numbered-paragraph> (deprecated) - listed under Changes for text:style-name, office-1437

We should also fix 
-  the variable capitalization of deprecated/Deprecated in headings
 - the variable use of parentheses.

**Comment by franciscave** [comment]
Alfred has pointed out that there are some layout issues, e.g. inconsistent line-breaks, in Appendix G in the ODF 1.4 Part 3 Working Draft.

**Comment by franciscave** [comment]
I have pushed changes to the Part 3 Appendix G and Part 4 Appendix A that remove un-needed list headings and blank lines.

A decision still needs to be made abou the Appendix in Part 2, in which no technical changes have been made (1 editorial), so no changes are listed. Should this Appendix be removed entirely?

**Comment by franciscave** [comment]
The TC agreed on 11/Dec/23 that the Appendix in Part 2 should be retained, containing a note that in ODF 1.4 there are no technical changes in Part 2. This issue can now be closed.
