### ISSUE TITLE
ODF Validator marks style:position="bottom center" as error

### ISSUE THREAD

**Issue by regina-henschel** [oasis-tcs/odf-tc#38]
The relevant part is
19.512.2  <style:background-image>
The style:position attribute specifies the position of a background image. Its value can be a **space-separated combination** of top, center or bottom for the vertical position and left, center or right for the horizontal position. The vertical and horizontal positions can be specified in any order. If one position is specified, the other position defaults to center.
[ImagePositionBottomCenter odf13strict.zip](https://github.com/oasis-tcs/odf-tc/files/6360473/ImagePositionBottomCenter.odf13strict.zip)

**Comment by mistmist** [comment]
oh, that is interesting... i've only seen this problem with a wrapper schema that uses <rng:include> to include the ODF schema, but with this document it happens directly.

i don't see a problem with the ODF schema; this is probably a bug in the Sun Multi-Schema Validator that is used by the ODF Toolkit Validator.

**Comment by svanteschubert** [comment]
The former Sun's Multi-Schema Validator was abandoned by Oracle. I will try to get control of the source code and bring it to TDF as our validator and ODFDOM's code generation depend on it.

**Comment by mistmist** [comment]
possible fix https://github.com/mistmist/msv/commit/8bc5db0c575d71e4739e0b78ef20171d2838c1ed
not sure how to get a new release of msv so that odftoolkit can depend on it...

**Comment by svanteschubert** [comment]
Oh, I got already a year ago the Maven artefact deployment rights from a former Sun colleague,  Kohsuke Kawaguchi.
I just need to fix another nasty issue that creates "some noise" during the code generation of ODFDOM...

**Comment by mistmist** [comment]
progress: Svante has thankfully done a new release of MSV that includes the bugfix
https://repo1.maven.org/maven2/net/java/dev/msv/msv-core/2022.7/
but it needs another release of ODF Toolkit to incorporate the MSV release

**Comment by svanteschubert** [comment]
As I stumbled over this issue again and asked myself if it can be closed, I would like to make an update:
Tested Reginas ODT (within the ZIP) with todays https://odfvalidator.org/
There is still an error:
![image](https://github.com/oasis-tcs/odf-tc/assets/825051/ad0729d3-0e4d-4baf-8c71-c159f2acfcef)

The test document contains in its style.xml the following attribute: 
**@style:position="bottom center"**

Which is valid by ODF 1.3: 
http://docs.oasis-open.org/office/OpenDocument/v1.3/os/schemas/OpenDocument-v1.3-schema-rng.html#9643

<**rng:attribute name="style:position**">
  <rng:choice>
    <rng:value>left</rng:value>
    <rng:value>center</rng:value>
    <rng:value>right</rng:value>
    <rng:value>top</rng:value>
    <rng:value>bottom</rng:value>
    <rng:list>
      <rng:ref name="horiBackPos"/>
      <rng:ref name="vertBackPos"/>
    </rng:list>
    <rng:list>
      **<rng:ref name="vertBackPos"/>
      <rng:ref name="horiBackPos"/>**
    </rng:list>
  </rng:choice>
</rng:attribute>

<rng:define name="vertBackPos">
<rng:choice>
  <rng:value>top</rng:value>
  <rng:value>center</rng:value>
  **<rng:value> bottom</rng:value>**
</rng:choice>
</rng:define>
<rng:define name="horiBackPos">
<rng:choice>
  <rng:value>left</rng:value>
  **<rng:value> center</rng:value>**
  <rng:value>right</rng:value>
</rng:choice>
</rng:define>
''

**Comment by svanteschubert** [comment]
I asked yesterday aside of the LibreOffice conference the admin to update the Java WAR of the validator (and fix the broken image link).
Today everything is fixed \o/
![image](https://github.com/oasis-tcs/odf-tc/assets/825051/2f5df26e-8b64-47d8-b8e8-74167d601774)
